config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: {
    sessions: 'users/sessions'
  }

  resources :bookmarks, only: [:create, :edit, :update] do
    get :new_import, on: :collection
    post :import,    on: :collection
    post :archive,   on: :member
  end
  resources :categories, only: [:index, :create, :show]
  resources :users, only: [:index, :create] do
    get :new_admin,     on: :collection
    post :create_admin, on: :collection
  end

  get 'search', to: 'bookmarks#search', as: 'search'
  root to: 'bookmarks#index'

  mount Sidekiq::Web => "/sidekiq"
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true

  scope :unarchived, -> { where(archived_at: nil) }

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  PAGE_SIZE = 10

  def index
    @categories = current_user.categories.order(name: :asc)

    @page = params[:p].to_i
    @page = 1 if @page == 0

    total = current_user.bookmarks.unarchived.count
    @last_page = [(total.to_f/PAGE_SIZE).ceil, 1].max
    @page = [@page, @last_page].min

    offset = (@page - 1)*PAGE_SIZE

    bookmarks = current_user.bookmarks.unarchived.order(created_at: :desc).offset(offset).limit(PAGE_SIZE).includes(:category)
    @bookmarks = bookmarks.map{ |b| BookmarkPresenter.new(b) }
    @has_more = @last_page > @page*PAGE_SIZE
    @start_index = (@page-1)*PAGE_SIZE + 1
    @end_index = [@page*PAGE_SIZE, total].min

  end

  def create
    bookmark = current_user.bookmarks.create!(bookmark_params)

    FetchLinkDetailsWorker.perform_async bookmark.id

    redirect_to root_path
  end

  def search
    @query = params[:q]
    query = "*" + @query + "*"

    @page = params[:p].to_i
    @page = 1 if @page == 0

    total = current_user.bookmarks.unarchived.search(query).records.count
    @last_page = [(total.to_f/PAGE_SIZE).ceil, 1].max
    @page = [@page, @last_page].min

    offset = (@page - 1)*PAGE_SIZE

    bookmarks = current_user.bookmarks.unarchived.search(query).records.offset(offset).limit(PAGE_SIZE).includes(:category)
    @bookmarks = bookmarks.map{ |b| BookmarkPresenter.new(b) }
    @has_more = @last_page > @page*PAGE_SIZE
    @start_index = (@page-1)*PAGE_SIZE + 1
    @end_index = [@page*PAGE_SIZE, total].min
  end

  def edit
    @categories = current_user.categories.order(name: :asc)
    @bookmark = current_user.bookmarks.find(params[:id])

    render layout: false
  end

  def update
    @bookmark = current_user.bookmarks.find(params[:id])
    permitted_params = params.require(:bookmark).permit(:category_id)
    @bookmark.update!(permitted_params)
    redirect_to request.referrer
  end

  def new_import
  end

  def import
    content = params[:content]

    current_user.import_bookmarks!(content)

    redirect_to root_path
  end

  def archive
    bookmark = current_user.bookmarks.find(params[:id])
    bookmark.update!({
      archived_at: DateTime.now,
    })
    redirect_to request.referrer
  end

  protected

  def bookmark_params
    params.require(:bookmark).permit(:link, :category_id)
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_add_modal.slim
.modal.fade#addModal tabindex="-1" aria-labelledby="addModal" aria-hidden="true"
  .modal-dialog
    .modal-content
      = form_with model: Bookmark.new, method: :post do |f|
        .modal-header
          h5.modal-title#addModalLabel Add bookmark...
          button.btn-close type="button" data-bs-dismiss="modal" aria-label="Close"
        .modal-body
          .form-floating
            = f.text_field :link, class: 'form-control', placeholder: 'URL'
            = f.label :link, label: 'URL'
          - unless @categories.blank?
            .py-2
              = f.select :category_id, @categories.map{|c| [c.name, c.id] }, {prompt: 'Uncategorised'}, {class: 'form-select'}
        .modal-footer
          = f.submit 'Add', class: 'btn btn-secondary'

app/views/bookmarks/_list.slim
= render partial: 'layouts/navbar', locals: {query: @query}

.container-lg.py-4
  - bookmarks.each_with_index do |b, i|
    .bookmark.d-flex.flex-column.pb-4.align-items-start
      = link_to b.link, target: '_blank', class: 'd-flex flex-wrap flex-row align-items-center flex-shrink-1 text-decoration-none fw-light text-dark' do
        .fs-3
          span.fs-5 = (@start_index + i).to_s + ". "
          span.fs-3 = b.title
      = link_to b.link, target: '_blank', class: 'd-flex flex-wrap flex-row align-items-center flex-shrink-1 text-decoration-none fw-light text-muted' do
        - if b.link_before.present?
          span.fw-lighter.fs-6.text-muted = b.link_before
        span.fw-normal.fs-6.text-dark = b.host
        - if b.link_after.present?
          span.fw-lighter.fs-6.text-muted = b.link_after
      .flex-row.spacing
        span.fw-light.fs-7.badge.text-muted.bg-light
          | Added
          =<> b.created_at
          | ago, under
        - if b.categorised?
          = link_to b.path_to_category do
            span.badge.bg-secondary.fs-7 = b.category_name
        - else
          span.badge.bg-secondary.fs-7 = b.category_name
      .flex-row.spacing
        = link_to 'edit', b.path_to_edit, class: 'ms-2 text-decoration-none text-info js-remote-modal-link'
        = link_to 'archive', b.path_to_archive, class: 'ms-2 text-decoration-none text-danger', data: {method: 'post', confirm: 'Are you sure?'}
  nav aria-label="Page navigation"
  ul.pagination.justify-content-center
    - if page != 1
      li.page-item
        = link_to 'First', page_link.call(p: 1), class: 'page-link link-success'
    - if page > 2
      li.page-item
        = link_to page-2, page_link.call(p: page-2), class: 'page-link link-success'
    - if page > 1
      li.page-item
        = link_to page-1, page_link.call(p: page-1), class: 'page-link link-success'
    li.page-item.disabled
      .page-link = page
    - if last_page > page
      li.page-item
        = link_to page+1, page_link.call(p: page+1), class: 'page-link link-success'
    - if last_page > (page+1)
      li.page-item
        = link_to page+2, page_link.call(p: page+2), class: 'page-link link-success'
    - if last_page != page
      li.page-item
        = link_to 'Last', page_link.call(p: last_page), class: 'page-link link-success'

= render partial: 'bookmarks/add_modal'

app/views/bookmarks/_remote_modal.slim
.modal.fade#remoteModal tabindex="-1" aria-labelledby="remoteModal" aria-hidden="true"
  .modal-dialog
    .modal-content
      .d-flex.flex-column.align-items-center.p-2
        h4.fs-5.py-2 Loading...
        .spinner-border role="status"
          span.visually-hidden Loading...
</div>

app/views/bookmarks/edit.slim
.p-2.d-flex.flex-column.align-items-stretch
  h3.text-center Choose new category
  .row.p-4
    - @categories.each do |c|
      .col-3
        = link_to bookmark_path(@bookmark, 'bookmark[category_id]' => c.id), method: :patch, class: 'text-decoration-none d-flex flex-column align-items-center' do
          i.fs-3.text-info class="bi-#{c.icon}"
          span.fs-6.text-info.text-decoration-none = c.name

app/views/bookmarks/index.slim
= content_for :title do
  | markit! / #{@page}
= render partial: 'bookmarks/list', locals: {bookmarks: @bookmarks, page: @page, last_page: @last_page, query: @query, page_link: ->(p:) { root_path(p: p) }}

app/views/bookmarks/new.slim
h3 New bookmark
= form_with scope: :bookmark, url: bookmarks_path do |f|
  = f.text_field :link
  = f.submit

app/views/bookmarks/new_import.slim
= content_for :title do
  | markit! / import
= render partial: 'layouts/navbar', locals: {query: @query}

.container-lg.py-4
  = form_with url: import_bookmarks_path, method: :post do |f|
    .form-input
      = f.label :content, class: 'form-label fs-5' do
        | Links to import
      = f.text_area :content, class: 'form-control'
    .form-actions.d-flex.flex-row.my-4
      = f.submit 'Import', class: 'btn btn-secondary flex-grow-1'

app/views/bookmarks/search.slim
= content_for :title do
  | markit! / #{params[:q]} / #{@page}
= render partial: 'bookmarks/list', locals: {bookmarks: @bookmarks, page: @page, last_page: @last_page, query: @query, page_link: ->(p:) { search_path(p: p) }}