config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: {
    sessions: 'users/sessions'
  }

  resources :bookmarks, only: [:create, :edit, :update] do
    get :new_import, on: :collection
    post :import,    on: :collection
    post :archive,   on: :member
  end
  resources :categories, only: [:index, :create, :show]
  resources :users, only: [:index, :create] do
    get :new_admin,     on: :collection
    post :create_admin, on: :collection
  end

  get 'search', to: 'bookmarks#search', as: 'search'
  root to: 'bookmarks#index'

  mount Sidekiq::Web => "/sidekiq"
end

app/models/user.rb
class User < ApplicationRecord
  CATEGORY_LIMIT = 20

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:username]

  has_many :bookmarks
  has_many :categories

  def self.admin
    User.find_by(username: 'admin')
  end

  def import_bookmarks!(content)
    raise 'invalid content' unless content.is_a?(String)

    lines = content.split("\n").map(&:chomp)
    lines.each do |line|
      link, timestamp_string = line.split(",")
      timestamp = begin
                    DateTime.parse(timestamp_string)
                  rescue
                    DateTime.now
                  end

      self.bookmarks.create!({
        link:       link,
        created_at: timestamp,
      })
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:create_admin, :new_admin, :create]

  def index
    authorize! :manage, User
    @users = User.all.order(created_at: :asc)
  end

  def create
    authenticate_user! if User.admin.present?

    User.create!(user_params)
    redirect_to users_path
  end

  def new_admin
  end

  def create_admin
    admin_params = params.require(:user).permit(:email, :password).merge({
      username: 'admin',
      is_admin: true,
    })
    User.create!(admin_params)
    redirect_to new_user_session_path
  end

  protected

  def user_params
    params.require(:user).permit(:username, :email, :is_admin, :password)
  end
end

app/views/users/_add_modal.slim
= content_for :title do
  | markit! / users
.modal.fade#userModal tabindex="-1" aria-labelledby="userModal" aria-hidden="true"
  .modal-dialog
    .modal-content
      = form_with model: User.new, method: :post do |f|
        .modal-header
          h5.modal-title#userModalLabel Add user...
          button.btn-close type="button" data-bs-dismiss="modal" aria-label="Close"
        .modal-body
          .form-floating
            = f.text_field :username, class: 'form-control', placeholder: 'Username'
            = f.label :username, label: 'Username'
          .form-floating.my-2
            = f.email_field :email, class: 'form-control', placeholder: 'Email'
            = f.label :email, label: 'Email'
          .form-floating.my-2
            = f.password_field :password, class: 'form-control', placeholder: 'Password'
            = f.label :password, label: 'Password'
          .form-check
            = f.check_box :is_admin, class: 'form-check-input'
            = f.label :is_admin, class: 'form-check-label', label: 'Admin user'
        .modal-footer
          = f.submit 'Add', class: 'btn btn-secondary'

app/views/users/index.slim
= render partial: 'layouts/navbar', locals: {query: nil}

.container-lg.py-4
  - if @users.blank?
    .row
      .card.col-4.offset-4
        .card-body.d-flex.flex-column.align-items-center
          p No users found
          = link_to 'Add new', '#userModal', class: 'btn btn-info', data: {'bs-toggle' => 'modal'}
  - else
    .row
      = link_to 'Add new', '#userModal', class: 'btn btn-info col-sm-12 col-lg-2 offset-lg-10', data: {'bs-toggle' => 'modal'}
      p
    table.table
      thead
        tr
          th scope="col" #
          th scope="col" Name
          th scope="col" Role
      tbody
        - @users.each_with_index do |u, i|
          tr
            th scope="row" = i+1
            td = u.username
            td = u.is_admin? ? 'Admin' : 'User'
= render partial: 'bookmarks/add_modal'
= render partial: 'categories/add_modal'
= render partial: 'users/add_modal'

app/views/users/new_admin.slim
// Navbar
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    = link_to 'markit!', '#', class: 'navbar-brand'
.container-lg.py-4
  .row
    .card.col-lg-4.offset-lg-4.col-12
      p.py-4.text-center No admin user found
      = form_with model: User.new, url: create_admin_users_path, method: :post do |f|
        .form-floating.my-2
          = f.email_field :email, class: 'form-control', placeholder: 'Email', required: true
          = f.label :email, label: 'Email'
        .form-floating.my-2
          = f.password_field :password, class: 'form-control', placeholder: 'Password', required: true
          = f.label :password, label: 'Password'
        .form-actions.my-4.d-flex.flex-row
          = f.submit 'Create admin user', class: 'btn btn-secondary flex-grow-1'