config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: {
    sessions: 'users/sessions'
  }

  resources :bookmarks, only: [:create, :edit, :update] do
    get :new_import, on: :collection
    post :import,    on: :collection
    post :archive,   on: :member
  end
  resources :categories, only: [:index, :create, :show]
  resources :users, only: [:index, :create] do
    get :new_admin,     on: :collection
    post :create_admin, on: :collection
  end

  get 'search', to: 'bookmarks#search', as: 'search'
  root to: 'bookmarks#index'

  mount Sidekiq::Web => "/sidekiq"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  
  has_many :bookmarks
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!

  PAGE_SIZE = 10

  def index
    @categories = current_user.categories.order(name: :asc)
  end

  def create
    raise "invalid icon" unless icons.include?(category_params[:icon]&.to_sym)
    raise "limit reached" if current_user.categories.count >= User::CATEGORY_LIMIT

    current_user.categories.create!(category_params)
    redirect_to categories_path
  end

  def show
    @category = current_user.categories.find(params[:id])
    @categories = current_user.categories.order(name: :asc)

    @page = params[:p].to_i
    @page = 1 if @page == 0

    total = current_user.bookmarks.count
    @last_page = [(total.to_f/PAGE_SIZE).ceil, 1].max
    @page = [@page, @last_page].min

    offset = (@page - 1)*PAGE_SIZE

    bookmarks = @category.bookmarks.order(updated_at: :desc).offset(offset).limit(PAGE_SIZE).includes(:category)
    @bookmarks = bookmarks.map{ |b| BookmarkPresenter.new(b) }
    @has_more = @last_page > @page*PAGE_SIZE
    @start_index = (@page-1)*PAGE_SIZE + 1
    @end_index = [@page*PAGE_SIZE, total].min
  end

  protected

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/views/categories/_add_modal.slim
= content_for :title do
  | markit! / categories
.modal.fade#categoryModal tabindex="-1" aria-labelledby="categoryModal" aria-hidden="true"
  .modal-dialog
    .modal-content
      = form_with model: Category.new, method: :post do |f|
        .modal-header
          h5.modal-title#categoryModalLabel Add category...
          button.btn-close type="button" data-bs-dismiss="modal" aria-label="Close"
        .modal-body
          .form-floating
            = f.text_field :name, class: 'form-control', placeholder: 'Name'
            = f.label :name, label: 'Name'
          .py-2
            h5 Icon
            .row
              - icons.each do |i|
                .col
                  .form-check.fs-4
                    = f.radio_button :icon, i, class: 'form-check-input'
                    i class="bi-#{i}"
        .modal-footer
          = f.submit 'Add', class: 'btn btn-secondary'

app/views/categories/index.slim
= render partial: 'layouts/navbar', locals: {query: nil}

.container-lg.py-4
  - if @categories.blank?
    .row
      .card.col-4.offset-4
        .card-body.d-flex.flex-column.align-items-center
          p No categories found
          = link_to 'Add new', '#categoryModal', class: 'btn btn-info', data: {'bs-toggle' => 'modal'}
  - else
    .row
      = link_to 'Add new', '#categoryModal', class: 'btn btn-info col-sm-12 col-lg-2 offset-lg-10', data: {'bs-toggle' => 'modal'}
      p
    table.table
      thead
        tr
          th scope="col" #
          th scope="col" Name
          th scope="col" Icon
          th scope="col" 
      tbody
        - @categories.each_with_index do |c, i|
          tr
            th scope="row" = i+1
            td = c.name
            td
              i.fs-3 class="bi-#{c.icon}"
            td
              = link_to "Open", category_path(c), class: 'btn btn-secondary'

= render partial: 'bookmarks/add_modal'
= render partial: 'categories/add_modal'

app/views/categories/show.slim
= content_for :title do
  | markit! / #{@category.name} / #{@page}
= render partial: 'bookmarks/list', locals: {bookmarks: @bookmarks, page: @page, last_page: @last_page, query: @query, page_link: ->(p:) { root_path(p: p) }}