config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: {
    sessions: 'users/sessions'
  }

  resources :bookmarks, only: [:create, :edit, :update] do
    get :new_import, on: :collection
    post :import,    on: :collection
    post :archive,   on: :member
  end
  resources :categories, only: [:index, :create, :show]
  resources :users, only: [:index, :create] do
    get :new_admin,     on: :collection
    post :create_admin, on: :collection
  end

  get 'search', to: 'bookmarks#search', as: 'search'
  root to: 'bookmarks#index'

  mount Sidekiq::Web => "/sidekiq"
end

app/views/layouts/_navbar.slim
// Navbar
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid.d-flex.flex-row
    = link_to 'markit!', root_path, class: 'navbar-brand'
    = link_to 'New bookmark', '#addModal', class: 'btn btn-secondary d-lg-none', data: {'bs-toggle' => 'modal'}
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarSupportedContent
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        li.nav-item
          = link_to 'Categories', categories_path, class: 'nav-link'
        li.nav-item
          = link_to 'Import', new_import_bookmarks_path, class: 'nav-link'
        - if can? :manager, User
          li.nav-item
            = link_to 'Users', users_path, class: 'nav-link'
      = form_with url: search_path, class: 'd-flex flex-grow-1 ms-2', method: :get do |f|
        = f.text_field :q, class: 'form-control me-2', type: 'search', placeholder: 'Search', aria: {label: 'Search'}, value: query
      = link_to 'New bookmark', '#addModal', class: 'btn btn-secondary d-none d-lg-block', data: {'bs-toggle' => 'modal'}
      hr
      = link_to 'Logout', destroy_user_session_path, class: 'btn btn-danger ms-2', data: {'bs-toggle' => 'modal', 'method' => 'delete', 'confirm' => 'Are you sure you want to logout?'}

app/views/layouts/application.slim
doctype html
html
  head
    title = yield(:title) || 'markit!'
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_pack_tag 'application', media: 'all'
    link rel="stylesheet" href="/css/bootstrap-icons.css" media="all"

  body
    .container-fluid.p-0
      = yield
    = render partial: 'bookmarks/remote_modal'

    = javascript_pack_tag 'application'